import { Persona } from './types';

export type PersonaTemplate = Omit<Persona, 'id' | 'isActive'>;

export const PERSONA_TEMPLATES: PersonaTemplate[] = [
  {
    name: 'Midwestern Mom',
    avatar: '👩‍🍳',
    interests: [
      'casserole recipes',
      'school fundraiser ideas',
      'minivan reviews 2026',
      'coupon deals grocery',
      'church potluck dishes',
      'gardening tips zone 5',
      'kids birthday party themes',
      'crockpot meals easy',
    ],
    schedule: { start: '06:30', end: '21:00', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'] },
    intensity: 'medium',
  },
  {
    name: 'Tech Bro',
    avatar: '💻',
    interests: [
      'cryptocurrency market today',
      'AI startup funding',
      'mechanical keyboard switches',
      'productivity apps 2026',
      'Tesla model updates',
      'YC demo day',
      'rust programming language',
      'standing desk reviews',
    ],
    schedule: { start: '10:00', end: '02:00', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    intensity: 'high',
  },
  {
    name: 'Retired Veteran',
    avatar: '🎣',
    interests: [
      'bass fishing lures',
      'VA benefits update',
      'woodworking plans beginner',
      'history channel documentaries',
      'weather forecast weekly',
      'best bird feeders',
      'classic car restoration',
      'local VFW events',
    ],
    schedule: { start: '05:00', end: '20:00', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    intensity: 'low',
  },
  {
    name: 'College Student',
    avatar: '📚',
    interests: [
      'study tips finals week',
      'cheap meal recipes',
      'dorm room organization',
      'part time jobs near me',
      'music festival lineup 2026',
      'best laptop for students',
      'scholarship applications',
      'thrift store hauls',
    ],
    schedule: { start: '11:00', end: '03:00', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    intensity: 'high',
  },
  {
    name: 'Fitness Influencer',
    avatar: '💪',
    interests: [
      'protein powder reviews',
      'HIIT workout routines',
      'meal prep Sunday',
      'lululemon new arrivals',
      'creatine benefits',
      'marathon training plan',
      'healthy smoothie recipes',
      'foam roller exercises',
    ],
    schedule: { start: '05:00', end: '22:00', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'] },
    intensity: 'medium',
  },
  {
    name: 'Conspiracy Theorist',
    avatar: '🛸',
    interests: [
      'UFO sightings recent',
      'government declassified documents',
      'alternative medicine remedies',
      'flat earth evidence',
      'area 51 news',
      'deep state theories',
      'ancient aliens history',
      'off grid living tips',
    ],
    schedule: { start: '22:00', end: '04:00', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    intensity: 'high',
  },
  {
    name: 'Suburban Dad',
    avatar: '🏡',
    interests: [
      'lawn care schedule spring',
      'best BBQ grill smoker',
      'home depot deals',
      'fantasy football rankings',
      'dad jokes clean',
      'garage organization ideas',
      'how to fix leaky faucet',
      'best cooler for tailgating',
    ],
    schedule: { start: '06:00', end: '22:00', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    intensity: 'medium',
  },
  {
    name: 'K-Pop Stan',
    avatar: '🎤',
    interests: [
      'BTS concert dates 2026',
      'kpop album unboxing',
      'korean skincare routine',
      'learn korean beginner',
      'kpop dance tutorial',
      'photocard trading',
      'korean street food recipes',
      'idol fashion outfits',
    ],
    schedule: { start: '15:00', end: '01:00', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    intensity: 'high',
  },
];
